### ISSUE TITLE
上传大文件时，移动和选中会卡顿

### ISSUE THREAD

**Issue by UncAnnyZ** [army8735/sketch-editor#8]
重现步骤:

点击上传按钮，选择一个大于100MB的文件进行上传。
上传完成后，尝试移动或选中该canvas里面的内容会卡死，缩小的时候比较明显。

环境信息:
操作系统：Mac
浏览器：Chrome

**Comment by army8735** [comment]
试试打开下tile

**Comment by UncAnnyZ** [comment]
感谢
